---
name: Internal - Common Continuous Integration tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@7034f6ae5bae1ec46a0108e8efb60d102e88961d # 0.37.2
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    with:
      codeql-languages: "" # FIXME: Let default value when CodeQL will be available (paid feature)
